'use server';

import { createSupabaseAdminClient } from '@/lib/supabase-admin';

interface FetchOrdersInput {
    shopId: string;
    page?: number;
    pageSize?: number;
    search?: string;
    status?: string;
}

export async function fetchOrders({ shopId, page = 1, pageSize = 20, search = '', status = '' }: FetchOrdersInput) {
    try {
        const supabase = createSupabaseAdminClient();
        const from = (page - 1) * pageSize;
        const to = from + pageSize - 1;

        let query = supabase
            .from('crm_orders')
            .select(`
                id, order_number, customer_name, customer_phone, customer_email,
                customer_address, status, subtotal, discount, shipping, total,
                notes, payment_method, payment_status, created_at, updated_at,
                crm_order_items(id)
            `, { count: 'exact' })
            .eq('shop_id', shopId)
            .order('created_at', { ascending: false })
            .range(from, to);

        if (search) {
            query = query.or(`order_number.ilike.%${search}%,customer_name.ilike.%${search}%,customer_phone.ilike.%${search}%`);
        }
        if (status) {
            query = query.eq('status', status);
        }

        const { data, error, count } = await query;
        if (error) {
            console.error('[vendor-orders] Fetch error:', error);
            return { error: 'Failed to fetch orders.', data: [], total: 0 };
        }

        const orders = (data || []).map((o) => {
            const rec = o as unknown as Record<string, unknown>;
            const items = rec.crm_order_items as unknown[];
            return { ...o, itemCount: items?.length || 0 };
        });

        return { error: null, data: orders, total: count || 0 };
    } catch (err) {
        console.error('[vendor-orders] Fetch error:', err);
        return { error: 'Unexpected error.', data: [], total: 0 };
    }
}

export async function getOrder(orderId: string, shopId: string) {
    try {
        const supabase = createSupabaseAdminClient();

        const { data, error } = await supabase
            .from('crm_orders')
            .select(`
                id, order_number, customer_name, customer_phone, customer_email,
                customer_address, status, subtotal, discount, shipping, total,
                notes, payment_method, payment_status, created_at, updated_at,
                crm_order_items(id, product_name, variant_name, quantity, unit_price, total_price)
            `)
            .eq('id', orderId)
            .eq('shop_id', shopId)
            .single();

        if (error || !data) return { error: 'Order not found.', data: null };
        return { error: null, data };
    } catch (err) {
        console.error('[vendor-orders] Get error:', err);
        return { error: 'Unexpected error.', data: null };
    }
}

interface CreateOrderInput {
    customerName: string;
    customerPhone?: string;
    customerEmail?: string;
    customerAddress?: string;
    notes?: string;
    paymentMethod?: string;
    items: Array<{
        productId: string;
        variantId?: string;
        productName: string;
        variantName?: string;
        quantity: number;
        unitPrice: number;
    }>;
}

export async function createOrder(shopId: string, input: CreateOrderInput) {
    try {
        const supabase = createSupabaseAdminClient();

        const subtotal = input.items.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0);
        const total = subtotal;

        const { data: order, error: orderErr } = await supabase
            .from('crm_orders')
            .insert({
                shop_id: shopId,
                order_number: '', // auto-generated by DB trigger
                customer_name: input.customerName,
                customer_phone: input.customerPhone || null,
                customer_email: input.customerEmail || null,
                customer_address: input.customerAddress || null,
                notes: input.notes || null,
                payment_method: input.paymentMethod || null,
                status: 'pending',
                payment_status: 'unpaid',
                subtotal,
                total,
            })
            .select('id, order_number')
            .single();

        if (orderErr || !order) {
            console.error('[vendor-orders] Create order error:', orderErr);
            return { error: 'Failed to create order.', data: null };
        }

        // Insert order items
        const orderItems = input.items.map(item => ({
            order_id: order.id,
            product_id: item.productId,
            variant_id: item.variantId || null,
            product_name: item.productName,
            variant_name: item.variantName || null,
            quantity: item.quantity,
            unit_price: item.unitPrice,
            total_price: item.unitPrice * item.quantity,
        }));

        const { error: itemsErr } = await supabase
            .from('crm_order_items')
            .insert(orderItems);

        if (itemsErr) {
            console.error('[vendor-orders] Create order items error:', itemsErr);
        }

        return { error: null, data: order };
    } catch (err) {
        console.error('[vendor-orders] Create error:', err);
        return { error: 'Unexpected error.', data: null };
    }
}

export async function updateOrderStatus(orderId: string, shopId: string, newStatus: string) {
    try {
        const supabase = createSupabaseAdminClient();

        const { error } = await supabase
            .from('crm_orders')
            .update({ status: newStatus })
            .eq('id', orderId)
            .eq('shop_id', shopId);

        if (error) {
            console.error('[vendor-orders] Update status error:', error);
            return { error: 'Failed to update order status.' };
        }

        return { error: null };
    } catch (err) {
        console.error('[vendor-orders] Update status error:', err);
        return { error: 'Unexpected error.' };
    }
}

export async function updatePaymentStatus(orderId: string, shopId: string, paymentStatus: string) {
    try {
        const supabase = createSupabaseAdminClient();

        const { error } = await supabase
            .from('crm_orders')
            .update({ payment_status: paymentStatus })
            .eq('id', orderId)
            .eq('shop_id', shopId);

        if (error) return { error: 'Failed to update payment status.' };
        return { error: null };
    } catch (err) {
        console.error('[vendor-orders] Update payment error:', err);
        return { error: 'Unexpected error.' };
    }
}
