export const featuredProducts = [
    {
        id: 1,
        name: 'DJI Agras T40',
        category: 'Agriculture Drone',
        price: '₹1,250,000',
        originalPrice: '₹14,00,000',
        rating: 4.8,
        reviews: 124,
        image: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=300&h=300&fit=crop',
        badge: 'Best Seller',
    },
    {
        id: 2,
        name: 'Hybrid Tomato Seeds - 500g',
        category: 'Seeds',
        price: '₹1,250',
        originalPrice: '₹1,500',
        rating: 4.6,
        reviews: 89,
        image: 'https://images.unsplash.com/photo-1592921870789-04563d55041c?w=300&h=300&fit=crop',
        badge: 'New',
    },
    {
        id: 3,
        name: 'Organic Neem Pesticide 5L',
        category: 'Garden Products',
        price: '₹850',
        originalPrice: '₹1,000',
        rating: 4.7,
        reviews: 256,
        image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&h=300&fit=crop',
        badge: 'Eco-Friendly',
    },
    {
        id: 4,
        name: 'Complete Rice Farming Kit',
        category: 'Crop Special Kit',
        price: '₹4,500',
        originalPrice: '₹5,200',
        rating: 4.5,
        reviews: 67,
        image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=300&h=300&fit=crop',
        badge: 'Bundle',
    },
    {
        id: 5,
        name: 'NPK Fertilizer 50kg',
        category: 'Agri Inputs',
        price: '₹1,800',
        originalPrice: '₹2,100',
        rating: 4.4,
        reviews: 312,
        image: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=300&h=300&fit=crop',
        badge: null,
    },
    {
        id: 6,
        name: 'Professional Pruning Shears',
        category: 'Agriculture Tools',
        price: '₹650',
        originalPrice: '₹800',
        rating: 4.9,
        reviews: 445,
        image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&h=300&fit=crop',
        badge: 'Top Rated',
    },
];

export const shopCategories = [
    {
        id: 'agriculture-drone',
        name: 'Agriculture Drone',
        icon: '🚁',
        description: 'Spraying & monitoring drones',
        count: 45,
        path: '/v2/shop/agriculture-drone',
        color: 'from-blue-50 to-blue-100 dark:from-blue-900/20 dark:to-blue-800/10',
    },
    {
        id: 'seeds',
        name: 'Seeds',
        icon: '🌱',
        description: 'Quality seeds for all crops',
        count: 320,
        path: '/v2/shop/seeds',
        color: 'from-amber-50 to-amber-100 dark:from-amber-900/20 dark:to-amber-800/10',
    },
    {
        id: 'garden-products',
        name: 'Garden Products',
        icon: '🧴',
        description: 'Pesticides, fertilizers & more',
        count: 186,
        path: '/v2/shop/garden-products',
        color: 'from-purple-50 to-purple-100 dark:from-purple-900/20 dark:to-purple-800/10',
    },
    {
        id: 'crop-special-kit',
        name: 'Crop Special Kit Products',
        icon: '📦',
        description: 'Complete crop care kits',
        count: 78,
        path: '/v2/shop/crop-special-kit',
        color: 'from-green-50 to-green-100 dark:from-green-900/20 dark:to-green-800/10',
    },
    {
        id: 'agri-inputs',
        name: 'Agri Inputs',
        icon: '🛍️',
        description: 'Essential farming inputs',
        count: 234,
        path: '/v2/shop/agri-inputs',
        color: 'from-orange-50 to-orange-100 dark:from-orange-900/20 dark:to-orange-800/10',
    },
    {
        id: 'agriculture-tools',
        name: 'Agriculture Tools',
        icon: '🔧',
        description: 'Hand tools & equipment',
        count: 156,
        path: '/v2/shop/agriculture-tools',
        color: 'from-slate-50 to-slate-100 dark:from-slate-800/30 dark:to-slate-700/20',
    },
];
