create table if not exists public.agri_news_cache (
  id bigint generated by default as identity primary key,
  items jsonb not null,
  live_event jsonb,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists agri_news_cache_fetched_at_idx on public.agri_news_cache (fetched_at desc);
