import type { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
    const baseUrl = 'https://www.miraitu.in';

    const routes = [
        { path: '/', priority: 1.0, changeFrequency: 'daily' as const },
        // '/home' omitted — it 301-redirects to '/'
        { path: '/home/about', priority: 0.8, changeFrequency: 'monthly' as const },
        { path: '/home/machinery', priority: 0.9, changeFrequency: 'daily' as const },
        { path: '/home/machinery/tractors', priority: 0.8, changeFrequency: 'daily' as const },
        { path: '/home/machinery/tractors/buy', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/machinery/tractors/sell', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/machinery/tractors/rent', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/machinery/tractors/new', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/machinery/harvesters', priority: 0.8, changeFrequency: 'daily' as const },
        { path: '/home/machinery/harvesters/buy', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/machinery/harvesters/sell', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/machinery/harvesters/rent', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/machinery/harvesters/new', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/machinery/jcb', priority: 0.8, changeFrequency: 'daily' as const },
        { path: '/home/machinery/jcb/buy', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/machinery/jcb/sell', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/machinery/jcb/rent', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/machinery/jcb/new', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/machinery/drones', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/drones/buy', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/drones/sell', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/drones/rent', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/drones/new', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/implements', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/implements/buy', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/implements/sell', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/implements/rent', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/implements/new', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/small-machineries', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/small-machineries/buy', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/small-machineries/sell', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/small-machineries/rent', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/small-machineries/new', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/machinery/compare', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/crops', priority: 0.9, changeFrequency: 'daily' as const },
        { path: '/home/crops/buy', priority: 0.8, changeFrequency: 'daily' as const },
        { path: '/home/crops/buy/grains', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/crops/sell', priority: 0.8, changeFrequency: 'daily' as const },
        { path: '/home/crops/sell/list', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/crops/mandi', priority: 0.8, changeFrequency: 'daily' as const },
        { path: '/home/crops/mandi/prices', priority: 0.8, changeFrequency: 'daily' as const },
        { path: '/home/crops/mandi/nearby', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/crops/mandi/trends', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/livestock', priority: 0.9, changeFrequency: 'daily' as const },
        { path: '/home/livestock/cattle', priority: 0.8, changeFrequency: 'daily' as const },
        { path: '/home/livestock/goats-sheep', priority: 0.8, changeFrequency: 'daily' as const },
        { path: '/home/livestock/poultry', priority: 0.8, changeFrequency: 'daily' as const },
        { path: '/home/livestock/fish', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/livestock/others', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/finance', priority: 0.8, changeFrequency: 'weekly' as const },
        { path: '/home/finance/loan', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/finance/insurance', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/shop', priority: 0.9, changeFrequency: 'daily' as const },
        // Individual shop category pages
        { path: '/home/shop/agriculture-drone', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/shop/seeds', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/shop/garden-products', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/shop/crop-special-kit', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/shop/agri-inputs', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/shop/agriculture-tools', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/shop/cold-press-oil', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/shop/solar-dry-products', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/shop/solar-dry-products/ralos', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/shop/organic-manure', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/shop/millets-grains', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/shop/honey-products', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/shop/spices-herbs', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/shop/dairy-products', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/shop/all', priority: 0.8, changeFrequency: 'daily' as const },
        { path: '/home/organic-store', priority: 0.8, changeFrequency: 'weekly' as const },
        { path: '/home/veterinary', priority: 0.8, changeFrequency: 'weekly' as const },
        { path: '/home/veterinary/semen-finder', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/land', priority: 0.8, changeFrequency: 'daily' as const },
        { path: '/home/land/buy', priority: 0.8, changeFrequency: 'daily' as const },
        { path: '/home/land/sell', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/land/lease', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/land/rent', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/services', priority: 0.8, changeFrequency: 'weekly' as const },
        // Individual service pages
        { path: '/home/services/harvester', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/services/drone-spray', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/services/farm-labours', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/services/transportation', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/services/technician', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/services/plumber', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/services/electrician', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/services/mechanic', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/services/milk-vendors', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/services/storage-godown', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/services/rent-machinery', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/services/soil-testing', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/borewell', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/fencing', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/cctv', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/protection', priority: 0.7, changeFrequency: 'weekly' as const },
        { path: '/home/toolbox', priority: 0.7, changeFrequency: 'daily' as const },
        // Individual toolbox pages
        { path: '/home/toolbox/crop-costing', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/toolbox/fertilizer-guide', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/toolbox/interest-calculator', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/toolbox/irrigation-calc', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/toolbox/land-area', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/toolbox/market-rates', priority: 0.6, changeFrequency: 'daily' as const },
        { path: '/home/toolbox/profit-estimator', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/toolbox/soil-testing', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/toolbox/unit-converter', priority: 0.6, changeFrequency: 'weekly' as const },
        { path: '/home/toolbox/weather-alerts', priority: 0.6, changeFrequency: 'daily' as const },
        { path: '/home/community', priority: 0.7, changeFrequency: 'daily' as const },
        { path: '/home/become-seller', priority: 0.8, changeFrequency: 'monthly' as const },
    ];

    return routes.map((route) => ({
        url: `${baseUrl}${route.path}`,
        lastModified: new Date(),
        changeFrequency: route.changeFrequency,
        priority: route.priority,
    }));
}
