export const featuredProducts = [
    {
        id: 1,
        name: 'DJI Agras T40',
        category: 'Agriculture Drone',
        price: '₹1,250,000',
        originalPrice: '₹14,00,000',
        rating: 4.8,
        reviews: 124,
        image: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=300&h=300&fit=crop',
        badge: 'Best Seller',
    },
    {
        id: 2,
        name: 'Hybrid Tomato Seeds - 500g',
        category: 'Seeds',
        price: '₹1,250',
        originalPrice: '₹1,500',
        rating: 4.6,
        reviews: 89,
        image: 'https://images.unsplash.com/photo-1592921870789-04563d55041c?w=300&h=300&fit=crop',
        badge: 'New',
    },
    {
        id: 3,
        name: 'Organic Neem Pesticide 5L',
        category: 'Garden Products',
        price: '₹850',
        originalPrice: '₹1,000',
        rating: 4.7,
        reviews: 256,
        image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&h=300&fit=crop',
        badge: 'Eco-Friendly',
    },
    {
        id: 4,
        name: 'Complete Rice Farming Kit',
        category: 'Crop Special Kit',
        price: '₹4,500',
        originalPrice: '₹5,200',
        rating: 4.5,
        reviews: 67,
        image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=300&h=300&fit=crop',
        badge: 'Bundle',
    },
    {
        id: 5,
        name: 'NPK Fertilizer 50kg',
        category: 'Agri Inputs',
        price: '₹1,800',
        originalPrice: '₹2,100',
        rating: 4.4,
        reviews: 312,
        image: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=300&h=300&fit=crop',
        badge: null,
    },
    {
        id: 6,
        name: 'Professional Pruning Shears',
        category: 'Agriculture Tools',
        price: '₹650',
        originalPrice: '₹800',
        rating: 4.9,
        reviews: 445,
        image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&h=300&fit=crop',
        badge: 'Top Rated',
    },
];

export const shopCategories = [
    {
        id: 'agriculture-drone',
        name: 'Agriculture Drone',
        icon: 'flight',
        isMatIcon: true,
        description: 'Spraying & monitoring drones',
        count: 45,
        path: '/home/shop/agriculture-drone',
        color: 'from-blue-50 to-blue-100 dark:from-blue-900/20 dark:to-blue-800/10',
    },
    {
        id: 'seeds',
        name: 'Seeds',
        icon: '\u{1F331}',
        isMatIcon: false,
        description: 'Quality seeds for all crops',
        count: 320,
        path: '/home/shop/seeds',
        color: 'from-amber-50 to-amber-100 dark:from-amber-900/20 dark:to-amber-800/10',
    },
    {
        id: 'garden-products',
        name: 'Garden Products',
        icon: '\u{1F9F4}',
        isMatIcon: false,
        description: 'Pesticides, fertilizers & more',
        count: 186,
        path: '/home/shop/garden-products',
        color: 'from-purple-50 to-purple-100 dark:from-purple-900/20 dark:to-purple-800/10',
    },
    {
        id: 'crop-special-kit',
        name: 'Crop Special Kit Products',
        icon: '\u{1F4E6}',
        isMatIcon: false,
        description: 'Complete crop care kits',
        count: 78,
        path: '/home/shop/crop-special-kit',
        color: 'from-green-50 to-green-100 dark:from-green-900/20 dark:to-green-800/10',
    },
    {
        id: 'agri-inputs',
        name: 'Agri Inputs',
        icon: '\u{1F6CD}\uFE0F',
        isMatIcon: false,
        description: 'Essential farming inputs',
        count: 234,
        path: '/home/shop/agri-inputs',
        color: 'from-orange-50 to-orange-100 dark:from-orange-900/20 dark:to-orange-800/10',
    },
    {
        id: 'agriculture-tools',
        name: 'Agriculture Tools',
        icon: '\u{1F527}',
        isMatIcon: false,
        description: 'Hand tools & equipment',
        count: 156,
        path: '/home/shop/agriculture-tools',
        color: 'from-slate-50 to-slate-100 dark:from-slate-800/30 dark:to-slate-700/20',
    },
    {
        id: 'cold-press-oil',
        name: 'Cold Press Oil',
        icon: 'water_drop',
        isMatIcon: true,
        description: 'Pure cold-pressed oils',
        count: 64,
        path: '/home/shop/cold-press-oil',
        color: 'from-yellow-50 to-yellow-100 dark:from-yellow-900/20 dark:to-yellow-800/10',
    },
    {
        id: 'solar-dry-products',
        name: 'Solar Dry Products',
        icon: 'sunny',
        isMatIcon: true,
        description: 'Sun-dried fruits & vegetables',
        count: 48,
        path: '/home/shop/solar-dry-products',
        color: 'from-red-50 to-red-100 dark:from-red-900/20 dark:to-red-800/10',
    },
    {
        id: 'organic-manure',
        name: 'Organic Manure',
        icon: 'compost',
        isMatIcon: true,
        description: 'Natural & organic fertilizers',
        count: 92,
        path: '/home/shop/organic-manure',
        color: 'from-lime-50 to-lime-100 dark:from-lime-900/20 dark:to-lime-800/10',
    },
    {
        id: 'millets-grains',
        name: 'Millets & Grains',
        icon: 'grain',
        isMatIcon: true,
        description: 'Farm-fresh millets & grains',
        count: 75,
        path: '/home/shop/millets-grains',
        color: 'from-emerald-50 to-emerald-100 dark:from-emerald-900/20 dark:to-emerald-800/10',
    },
    {
        id: 'honey-products',
        name: 'Honey & Bee Products',
        icon: 'hive',
        isMatIcon: true,
        description: 'Raw honey & bee farming kits',
        count: 38,
        path: '/home/shop/honey-products',
        color: 'from-amber-50 to-amber-100 dark:from-amber-900/20 dark:to-amber-800/10',
    },
    {
        id: 'spices-herbs',
        name: 'Spices & Herbs',
        icon: 'spa',
        isMatIcon: true,
        description: 'Farm-direct spices & herbs',
        count: 110,
        path: '/home/shop/spices-herbs',
        color: 'from-rose-50 to-rose-100 dark:from-rose-900/20 dark:to-rose-800/10',
    },
];
